apiVersion: v1
kind: Service
metadata:
  name: selenium-node-chrome-service
spec:
  type: NodePort
  selector:
    app: selenium-node-chrome
  ports:
    - protocol: TCP
      port: 4444
      nodePort: 30001