apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  labels:
    app: postgresql-db
spec:
#  type: LoadBalancer
#  type: ClusterIP
  type: NodePort
  ports:
  - name: postgres
    port: 5432
    targetPort: 5432 
    nodePort: 31333
  selector:
    app: postgresql-db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deployment
  labels:
    app: postgresql-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-db
  template:
    metadata:
      labels:
        app: postgresql-db
    spec:
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgresql-pvc
      containers:
        - name: postgresql-container
          env:
          - name: POSTGRES_PASSWORD
            value: Pass123!
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_DB
            value: mydb
          image: postgres:latest
          ports:
            - containerPort: 5432
              name: postgresql-db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage
              
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
  selector:
    matchLabels:
      app: postgresql-db
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol
  labels:
    app: postgresql-db
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  hostPath:
    path: /mnt/postgres-db

