apiVersion: apps/v1
kind: Deployment
metadata:
  name: mssql
  labels:
    app: mssql
spec:
  selector:
    matchLabels:
      app: mssql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mssql
    spec:
      containers:
        - image: mcr.microsoft.com/mssql/server:2017-latest
          resources:
            requests:
              cpu: 1
              memory: 500Mi
          name: mssql
          envFrom:
            - secretRef:
                name: mssql-secret
          ports:
            - containerPort: 1433
              name: mssql
          volumeMounts:
            - name: mssql-pers-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: mssql-pers-storage
          persistentVolumeClaim:
            claimName: mssql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    app: mssql-db
spec:
  type: NodePort
  ports:
    - name: mssql
      port: 1433
      targetPort: 1433
      nodePort: 32433
  selector:
    app: mssql
---
apiVersion: v1
kind: Secret
metadata:
  name: mssql-secret
data:
  SA_PASSWORD: UGFzc3dvcmQxMjMh
  ACCEPT_EULA: WQ==
# from inside of container: mssql-cli -U SA -P Password123!
# from outside of container: mssql-cli -U SA -S 192.168.49.2,32433kind: PersistentVolumeClaim
---
apiVersion: v1
metadata:
  name: mssql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 1Gi
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: mssql-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mssql
