apiVersion: v1
kind: Service
metadata:
  name: selenium-firefox-service
spec:
  type: NodePort
  selector:
    app: selenium-firefox
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 32111