apiVersion: v1
kind: Service
metadata:
  name: selenium-chrome-service
spec:
  type: NodePort
  selector:
    app: selenium-chrome
  ports:
    - protocol: TCP
      port: 4444
      targetPort: 4444
      nodePort: 32222