apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub-deploy
  labels:
    app: selenium-hub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
        - name: selenium-hub-host
          image: kostcker/selenium-hub
          ports:
            - containerPort: 4444